#!/usr/bin/env python3
"""Rasterise a monospace TTF into the bitmap tables used by the web simulator.

The simulator's M5GFX compatibility layer has no text rendering, but the
firmware UI leans on it heavily.  Rather than hand-transcribe a bitmap font we
rasterise Consolas once, at metrics chosen to match M5GFX's built-in fonts:

    Font2 ->  8 x 16   (advance 8, the metric the UI layout assumes)
    Font4 -> 16 x 26

Matching the advance matters more than matching the glyph shapes: if the
simulated text were wider than the real font, labels would overflow their
buttons and the screenshots would misrepresent the firmware.

Usage:  python sim/tools/make_font.py > sim/sim_font_data.h
"""

import sys

from PIL import Image, ImageDraw, ImageFont

FIRST, LAST = 0x20, 0x7E
CANDIDATES = [
    r"C:\Windows\Fonts\consola.ttf",
    r"C:\Windows\Fonts\cour.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
]


def load_font(px):
    for path in CANDIDATES:
        try:
            return ImageFont.truetype(path, px)
        except OSError:
            continue
    raise SystemExit("no usable monospace TTF found")


def fit_font(cell_w, cell_h):
    """Largest point size whose glyphs still fit the cell."""
    best = None
    for px in range(4, cell_h * 2 + 4):
        font = load_font(px)
        w = font.getbbox("M")[2] - font.getbbox("M")[0]
        ascent, descent = font.getmetrics()
        if w <= cell_w and ascent + descent <= cell_h:
            best = (px, font, ascent)
    if best is None:
        raise SystemExit(f"nothing fits {cell_w}x{cell_h}")
    return best


def render(cell_w, cell_h, threshold=110):
    px, font, ascent = fit_font(cell_w, cell_h)
    rows_per_glyph = cell_h
    bytes_per_row = (cell_w + 7) // 8
    out = []
    for code in range(FIRST, LAST + 1):
        img = Image.new("L", (cell_w, cell_h), 0)
        d = ImageDraw.Draw(img)
        # Nudge right by one pixel: Consolas sits hard against the left edge at
        # small sizes and the extra column keeps glyphs from touching.
        d.text((1, 0), chr(code), font=font, fill=255)
        rows = []
        for y in range(rows_per_glyph):
            value = 0
            for x in range(cell_w):
                if img.getpixel((x, y)) >= threshold:
                    value |= 1 << (cell_w - 1 - x)
            rows.append(value)
        out.append(rows)
    return px, bytes_per_row, out


def emit(name, cell_w, cell_h):
    px, bpr, glyphs = render(cell_w, cell_h)
    ctype = "uint8_t" if bpr == 1 else "uint16_t"
    print(f"// {name}: {cell_w}x{cell_h} cells, rasterised from a {px}px monospace face")
    print(f"static const {ctype} {name}[{len(glyphs)}][{cell_h}] = {{")
    for code, rows in zip(range(FIRST, LAST + 1), glyphs):
        ch = chr(code)
        label = "'\\''" if ch == "'" else (r"'\\'" if ch == "\\" else f"'{ch}'")
        body = ",".join(f"0x{r:0{bpr*2}X}" for r in rows)
        print(f"    {{{body}}},  // {label}")
    print("};")
    print()


def main():
    print("// Generated by sim/tools/make_font.py - do not edit by hand.")
    print("#pragma once")
    print("#include <stdint.h>")
    print()
    print(f"#define SIM_FONT_FIRST 0x{FIRST:02X}")
    print(f"#define SIM_FONT_LAST  0x{LAST:02X}")
    print()
    emit("kSimFontSmall", 8, 16)
    emit("kSimFontLarge", 16, 26)
    return 0


if __name__ == "__main__":
    sys.exit(main())
